
<div id="search" class="chearboth" style="width:100%" >
    <div class="" style="">
        <div class="centerinfo" >
            <div class="centersearch">
                <div class="searchinput" >
                    <input type="hidden" id="keyword_py" name="keyword_py" value=""/>
                    <div class="inputone fl"  >
                        <input type="text" id="keyword" name="keyword" value="" onFocus="delval()" onBlur="addval()" class="searchinput" />
                    </div>
                    <div class="inputtwo fl">
                        <input value="&nbsp;&nbsp;&nbsp;搜 索"  type="submit" class="searchbutton" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>