<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('登录')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/mainlayout/common/favicon.ico'])
        ->prependStylesheet($this->basePath('css/mainlayout/Wopop_files/style.css'))
        ->prependStylesheet($this->basePath('css/mainlayout/Wopop_files/userpanel.css'))
        ->prependStylesheet($this->basePath('css/mainlayout/Wopop_files/style_log.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/mainlayout/side.js'))
        ->prependFile($this->basePath('js/mainlayout/jquery-1.10.1.min.js'))
    ?>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
</head>

<body class="login" mycollectionplug="bind">
<?= $this->content ?>
<?php
$form->setAttribute('action', $this->url('auth', ['action' => 'index']));
$form->setAttribute('class','loginAction');
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="login_m">
    <div class="login_boder">
        <div class="login_padding" id="login_model">
            <h2>用户名</h2>
            <label>
                <?php echo $this->formRow($form->get('username'));?>
            </label>
            <h2>密码</h2>
            <label>
                <?php echo $this->formRow($form->get('passwd'));?>
            </label>
            <div class="rem_sub">
                <div class="rem_sub_l">
                    <?php echo $this->formRow($form->get('isSavePwd')); ?>
                    <label for="checkbox">记住</label>
                </div>
                <label>
                    <?php echo $this->formRow($form->get('submit')); ?>
                </label>
            </div>
        </div>

        <!--login_padding  Sign up end-->
    </div><!--login_boder end-->
</div><!--login_m end-->
<br> <br>

</body></html>