<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('title')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/mainlayout/common/favicon.ico'])
        ->prependStylesheet($this->basePath('css/wechat/left-menu.css'))
        ->prependStylesheet($this->basePath('css/wechat/style.css'))
    ?>
    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/mainlayout/jquery-1.10.1.min.js'))
    ?>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
</head>
<body>
<div class="contentmanage">
    <div class="developer">
        <div class="appTitle normalTitle2">
            <div class="vipuser">
                <div class="logo">
                    <a href="/index.php?g=User&m=Function&a=welcome&token=znspul1489384614"><img src="./tpl/User/default/common/images/portrait.jpg" width="100" height="100" /></a>
                </div>
                <div id="nickname">
                    <strong><a href="/index.php?g=User&m=Function&a=welcome&token=znspul1489384614">泉水叮咚微商城</a></strong><a href="#" target="_blank" class="vipimg vip-icon3" title=""></a></div>
                <div id="weixinid">微信号:qsddw-mall</div>
            </div>
            <div class="accountInfo">
                <table class="vipInfo" width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td><strong>VIP有效期：</strong>2019-12-08</td>
                        <td><strong>图文自定义：</strong>0/50000</td>
                        <td><strong>活动创建数：</strong>0/10000</td>
                        <td><strong>请求数：</strong>0/500000</td>
                    </tr>
                    <tr>
                        <td><strong>请求数剩余：</strong>500000</td>
                        <td><strong>已使用：</strong>0</td>
                        <td><strong>当月赠送请求数：</strong>500000</td>
                        <!-- <td><strong>当月剩余请求数：</strong>500000</td> -->
                        <td><strong>当月剩余请求数：</strong>500000</td>
                    </tr>

                </table>
            </div>
            <div class="clr"></div>
        </div>
        <div class="tableContent">
            <!--左侧-->
            <div  class="sideBar" id="sideBar">
                <div class="catalogList">
                    <ul id="menu">
                        <a class="nav-header" style="border-top:none !important;"><b class="base"></b>基础设置</a>
                        <ul class="ckit">
                            <li class="subCatalogList"> <a href="#">功能管理</a></li>
                            <li class="subCatalogList"> <a href="#">关注时回复与帮助</a></li>
                            <li class="subCatalogList"> <a href="#">微信－文本回复</a></li>
                            <li class="subCatalogList"> <a href="#">微信－图文回复</a></li>
                            <li class="subCatalogList"> <a href="#">微信－图文编辑器</a><span class="new"></span></li>
                            <li class="subCatalogList"> <a href="#">微信－多图文回复</a></li>
                            <li class="subCatalogList"> <a href="#">微信－语音回复</a></li>
                            <li class="subCatalogList"> <a href="#">微信－群发消息</a><span class="new"></span></li>
                            <li class="subCatalogList"> <a href="#">微信－模板消息</a><span class="new"></span></li>
                            <li class="selected"> <a href="/function/menu/<?=$this->id?>">自定义菜单</a></li>
                            <li class="subCatalogList"> <a href="#">自动获取粉丝信息</a><span class="new"></span></li>
                            <li class="subCatalogList"> <a href="#">在线客服配置</a><span class="new"></span></li>
                        </ul>
                    </ul>
                </div>
            </div>
            <!--左侧end-->
            <!--右侧-->
            <div class="content">
                <ul class="gzh">
                    <li class="guanzhu">
                        <a title="公众号">
                            1                <p>公众号</p>
                        </a>
                    </li>
                    <li class="huiyuanka">
                        <a title="会员卡">
                            0                <p>会员卡</p>
                        </a>
                    </li>
                    <li class="liulan">
                        <a title="图文消息">
                            0                <p>图文消息</p>
                        </a>
                    </li>
                    <li class="fangke">
                        <a title="微活动">
                            0                <p>微活动</p>
                        </a>
                    </li>
                    <div class="clr"></div>
                </ul>
            </div>
            <!--右侧end-->
            <div style="clear: both"></div>
        </div>
    </div>
</div>
</body>
</html>

<script>
    $(document).ready(function(){
        $(".nav-header").mouseover(function(){
            $(this).addClass('navHover');
        }).mouseout(function(){
            $(this).removeClass('navHover');
        }).click(function(){
            $(this).toggleClass('nav-header-current');
            $(this).next('.ckit').slideToggle();
        })
    });
</script>