<?php if ($this->pageCount):
    $query=$this->query;
    $act=$this->act;
    if(empty($act)){
        $act=[];
    }
?>
    <div>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)):
                $query['page']=$this->previous;?>
                <li>
                    <a href="<?= $this->url($this->route,$act, ['query' => $query]) ?>">
                        &lt;&lt;
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        &lt;&lt;
                    </a>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current):
                    $query['page']=$page;?>
                    <li>
                        <a href="<?= $this->url($this->route,$act, ['query' => $query]) ?>">
                            <?= $page ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?= $page ?></a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <?php $query['page']=$this->next;?>
                    <a href="<?= $this->url($this->route,$act, ['query' => $query]) ?>">
                        &gt;&gt;
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        &gt;&gt;
                    </a>
                </li>
            <?php endif ?>
        </ul>
    </div>
<?php endif ?>