<?php
/*
This is menu list loop
 */ ?>

<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="/power" title="二级分类" target="right">二级分类</a>
        <a href="/wechat" title="二级分类" target="right">公众号管理</a>
        <a href="" title="二级分类" class="active">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>
<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>
<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>
<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>
<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>
<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>
<dl>
    <dt><span>一级分类名称</span></dt>
    <dd><a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a>
        <a href="" title="二级分类">二级分类</a></dd>
</dl>