<li class="nav01"><a href="" title="主页管理">主页管理</a></li>
<li class="nav02"><a href="" title="系统管理">系统管理</a></li>
<li class="active nav03"><a href="" title="合同信息">合同信息</a></li>
<li class="nav04"><a href="" title="基础数据">基础数据</a></li>
<li class="nav05"><a href="" title="预算管理">预算管理</a></li>
<li class="nav06"><a href="" title="项目管理">项目管理</a></li>
<li class="nav07"><a href="" title="资金支付-发票">资金支付-发票</a></li>
<li class="nav08"><a href="" title="产品管理信息">产品管理信息</a></li>