<?php $this->headLink()->prependStylesheet($this->basePath('css/wechat/style.css')) ?>
<?php
$form->setAttribute('action', $this->url('wechat', ['action' => 'add']));
$form->prepare();
?>
<div class="content">
    <div class="cLineB">
        <h4>添加微信公众号</h4>
    </div>
    <?php echo $this->form()->openTag($form);?>
    <?php echo $this->formHidden($form->get('id'))?>
        <div class="msgWrap">
            <table class="userinfoArea" border="0" cellspacing="0" cellpadding="0" width="100%">
                <thead>
                    <tr>
                        <th><span class="red">*</span>公众号名称：</th>
                        <td><?php echo $this->formRow($form->get('wxname'))?>
                        </td>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <th><span class="red">*</span>公众号原始id：</th>
                    <td><?php echo $this->formRow($form->get('wxid'))?>　<span class="red"> 请认真填写，错了不能修改。</span>比如：gh_423dwjkeww3 <a href="/static/getoid.htm" target="_blank"><img src="/images/help.png" class="vm helpimg" title="帮助"></a></td>
                </tr>
                <tr>
                    <th><span class="red">*</span>微信号：</th>
                    <td><?php echo $this->formRow($form->get('weixin'))?>　比如：lentu123 </td>
                </tr>
                <tr>
                    <th><span class="red">*</span>AppID（公众号）：</th>
                    <td><?php echo $this->formRow($form->get('appid'))?>　用于自定义菜单等高级功能，必填 </td>
                </tr>
                <tr>
                    <th><span class="red">*</span>AppSecret：</th>
                    <td><?php echo $this->formRow($form->get('appsecret'))?>　用于自定义菜单等高级功能，必填 </td>
                </tr>
                <tr>
                    <th><span class="red">*</span>二维码：</th>
                    <td>
                        <?php echo $this->formRow($form->get('qrcode'))?>
                        <a href="###" onclick="upyunPicUpload('qr',500,500,'admin')" class="a_upload">上传</a>
                        <a href="###" onclick="viewImg('qr')">预览</a>
                    </td>
                </tr>
                <tr>
                    <th><span class="red"></span>微信号类型：</th>
                    <td>
                        <?php //echo $this->formRow($form->get('typeid'))
                        $typeselect=$form->get('typeid');
                        echo $this->formRow($typeselect);
                        ?>　认证服务号是指每年向微信官方交300元认证费的公众号 </td>
                </tr>
                <tr>
                    <th><span class="red">*</span>头像地址（url）:</th>
                    <td><?php echo $this->formRow($form->get('headerpic'))?>　请填写图片外链地址 <a onclick="alert('请填写以jpg,png,gif,bmp等后缀的图文')" target="_blank"><img src="/images/help.png" class="vm helpimg" title="帮助"></a></td>
                </tr>
                <tr>
                    <th>消息加密方式</th>
                    <td><?php echo $this->formRow($form->get('EncodeType'))?></td>
                </tr>
                <tr>
                    <th>AesEncodingKey</th>
                    <td><?php echo $this->formRow($form->get('AesEncodingKey'))?>　加密消息的AesEncodingKey，可为空系统自动生成</td>
                </tr>
                <tr>
                    <th><span class="red">*</span>TOKEN</th>
                    <td><?php echo $this->formRow($form->get('token'))?>　(填写你的公众号)例：weimicmsweixin,请勿填写文,或者其它特殊字符，此处token和腾讯平台必须一致!</td>
                </tr>

                <tr>
                    <th></th>
                    <td><?=$this->formSubmit($form->get('submit'))?></td>
                </tr>
                </tbody>
            </table>

        </div>
    <?php echo $this->form()->closeTag()?>
</div>