<?= $this->headLink()->prependStylesheet($this->basePath('css/wechat/style.css')) ?>
<div class="content">
    <div class="usercontent">
        <ul>
            <li class="addli">
                <a class="addwx" style="background-color:#7CBAE5" title="添加公众号" href="/wechat/add">绑定公众号</a>
            </li>
            <div class="clr"></div>
        </ul>
        <div class="clr"></div>
    </div>
    <div class="msgWrap">
        <table class="ListProduct" border="0" cellspacing="0" cellpadding="0" width="100%">
            <thead>
            <tr>
                <th>公众号名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <tr></tr>
            <?php foreach ($this->paginator as $rows) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($rows->wxname);?>
                </td>
                <td class="norightborder">　
                    <a href="<?php echo $this->url('wechat',['action'=>'edit','id'=>$rows->id])?>">编辑</a>
                    <a href="<?=$this->url('wechat',['action'=>'delete','id'=>$rows->id])?>" onclick="return confirm('确定删除吗？');">删除</a>
                    <a href="/index.php?g=User&amp;m=Function&amp;a=welcome&amp;id=1&amp;token=znspul1489384614" class="btnGreens">功能管理</a>
                </td>
            </tr>
            <?php endforeach;?>
            </tbody>
        </table>

    </div>
    <br>
    <div class="cLine">
        <div class="pageNavigator right">
            <div class="pages">
                <?= $this->paginationControl(
                   // The paginator object:
                    $this->paginator,
                    // The scrolling style:
                    'sliding',
                    // The partial to use to render the control:
                    'partial/paginator',
                    // The route to link to when a user clicks a control link:
                    ['route' => 'wechat']
                ) ?>
            </div>
        </div>
        <div class="clr"></div>
    </div>
</div>
